apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-teller-backend
  labels:
    app: bank-teller-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-teller-backend
  template:
    metadata:
      labels:
        app: bank-teller-backend
    spec:
      containers:
        - name: bank-teller-backend
          image: registry.ncloud.com/your-ncp-project-id/bank-teller-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: url
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: key
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bank-teller-backend-service
spec:
  selector:
    app: bank-teller-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
